In [ ]:
import numpy as np
x = np.linspace(0, 10, 5)
print(x)


[ 0.   2.5  5.   7.5 10. ]


In [ ]:
import numpy as np
#single random float value from 0 to 1
np.random.rand
#1-D array with float values from 0 10 1
np.random.rand(10)
#2-D array with float values from 0 10
np.random.rand(3,5)
#3-D array with float values from 0 10 1
np.random.rand(2,3,4)

array([[[0.40366746, 0.06809805, 0.57361903, 0.25315063],
        [0.54384874, 0.03554262, 0.08393042, 0.18542735],
        [0.06125576, 0.3575183 , 0.95944954, 0.98682605]],

       [[0.06345902, 0.73166045, 0.19834683, 0.22428262],
        [0.84026925, 0.26439881, 0.68409612, 0.65034075],
        [0.16046462, 0.97328362, 0.83003587, 0.33690058]]])

In [ ]:
import numpy as np
#random float value in the given customized range
np.random.uniform(10,20)
#1-D array with customized range range of float values
np.random.uniform(10,20,size=10)
#2-D array with customized range range of float values
np.random.uniform(10,20,size=(3,5))
#3-D array with customized range range of float values
np.random.uniform(10,20,size=(2,3,4))

array([[[15.5021172 , 15.33792151, 19.46475041, 15.63085409],
        [10.46034542, 18.57059305, 17.8582729 , 15.22865521],
        [11.7181306 , 16.22787943, 11.32254261, 14.7287154 ]],

       [[12.00848513, 14.39869628, 18.23289196, 16.04948251],
        [19.10987773, 12.95325363, 18.12021518, 18.31983061],
        [10.33747305, 11.66119514, 12.69003701, 10.55371961]]])

In [ ]:
import numpy as np
#single float value including -ve value also
a=np.random.randn()
print(a)
#1-D array with mean 0 and stand deviation
a=np.random.randn(10)
print(a)
#2-D array with mean 0 and stand deviation
a=np.random.randn(2,3)
print(a)
#3-D array with mean 0 and stand deviation
a=np.random.randn(2,3,4)
print(a)

0.61746749960587
[-0.42573318 -0.08513066  0.17764871  0.26015622 -1.61068153 -0.12261878
 -1.06087088 -1.90247253  0.20308676 -0.19540791]
[[-1.11861169e+00  1.68853673e+00  9.90157761e-02]
 [-3.63475530e-01 -1.32905595e-03  1.65175741e+00]]
[[[-2.212104    0.17146255 -1.43205198  0.29351347]
  [-0.92212726 -1.17088014 -0.2915554   0.04690744]
  [ 0.61784088 -0.93878147 -1.27349552 -0.15590119]]

 [[ 0.66592965  1.67898735  1.38538109  1.38905677]
  [-0.97661178 -0.05061529 -0.17832744 -1.2268952 ]
  [-1.05804983 -1.93188594 -2.10384606  0.14521131]]]


What is pandas?
Pandas is a python library used for data analysis and manipulatio .
It provides two main data structures
==>Series:One dimensional array like object 
==>DataFrame:Two dimensional table like structure

What is a Series?
A pandas series is like a column in a spreadsheet or a 1-D array with labels (called indices).
Pandas Series is a versatile tool for managing and analyzing 1-D data.Its combination of labels and values
syntax to generate a series in pandas
==>pd.Series(data,index,dtype)

In [ ]:
import pandas as pd
#from a list
s1=pd.Series([10,20,30,40])
print(s1)

0    10
1    20
2    30
3    40
dtype: int64


In [ ]:
import pandas as pd 
#from a list with custom index
s2=pd.Series([10,20,30],index=['a','b','c'])
print(s2)


a    10
b    20
c    30
dtype: int64


In [ ]:
import pandas as pd
#from a dictonary
s3=pd.Series({"a":100,"b":200,"c":300})
print(s3)

a    100
b    200
c    300
dtype: int64


In [ ]:

y=[chr(i) for i in range(65,75)]
print(y)

np.random.seed(10)
x=np.random.randint(10,31,size=10)
s1=pd.Series(x,index=y)
print(s1)

In [ ]:
s4=pd.Series(5,index=["x","y","z"])
print(s4) #scalar

x    5
y    5
z    5
dtype: int64


In [ ]:
import numpy as np
import pandas as pd
s1=pd.Series([10,20,30,40,50])
print(s1)
print(s1.index)
print(s1.values)
print(s1.dtype)
print(s1.shape)
print(s1.size)

0    10
1    20
2    30
3    40
4    50
dtype: int64
RangeIndex(start=0, stop=5, step=1)
[10 20 30 40 50]
int64
(5,)
5


In [ ]:
import numpy as np
import pandas as pd

# Create a Pandas Series with custom labels
s1 = pd.Series([10, 20, 30, 40, 50], index=['A', 'B', 'C', 'D', 'E'])

# Basic info
print(s1)
print(s1.values)      # Only values
print(s1.dtype)       # Data type
print(s1.shape)       # Shape of the series
print(s1.size)        # Number of elements

# Indexing and slicing
print(s1)             
print(s1['A'])        # Access using label
print(s1[0:4])        # Positional slicing
print(s1[['A', 'D']]) # Access using multiple labels
print(s1.iloc[0])     # First element using iloc
print(s1.iloc[0:4])   # Positional slicing using iloc
print(s1.iloc[[0, 3]])# Access positions 0 and 3

# Conditional selections
print(s1[s1 > 30])      # Elements greater than 30
print(s1[s1 % 2 == 0])  # Even numbers


A    10
B    20
C    30
D    40
E    50
dtype: int64
[10 20 30 40 50]
int64
(5,)
5
A    10
B    20
C    30
D    40
E    50
dtype: int64
10
A    10
B    20
C    30
D    40
dtype: int64
A    10
D    40
dtype: int64
10
A    10
B    20
C    30
D    40
dtype: int64
A    10
D    40
dtype: int64
D    40
E    50
dtype: int64
A    10
B    20
C    30
D    40
E    50
dtype: int64


In [ ]:
import numpy as np
import pandas as pd

# Create a Pandas Series with custom labels
s1 = pd.Series([10, 20, 30, 40, 50])
print(s1)
print('=======================')
s2=pd.Series(['10','20','30'],index=['a','b','c'])
print(s2)
print(s1+10)#add 10 to each element
print(s1*2)#multiply each elemnt by 2
print(s1+s2)#align addition baed on index

0    10
1    20
2    30
3    40
4    50
dtype: int64
a    10
b    20
c    30
dtype: object
0    20
1    30
2    40
3    50
4    60
dtype: int64
0     20
1     40
2     60
3     80
4    100
dtype: int64
0    NaN
1    NaN
2    NaN
3    NaN
4    NaN
a    NaN
b    NaN
c    NaN
dtype: object


In [ ]:
import numpy as np
import pandas as pd

# Create a Pandas Series with custom labels
s1 = pd.Series([10, 20,10, 30, 40, 30,50])
print(s1)
print(s1.head(2))#first two elements
print(s1.tail(2))#last two elements
print(s1.describe())#all statistical details
print(s1.mean())
print(s1.sum())
print(s1.min())
print(s1.max())
print(s1.unique())
print(s1.value_counts())#frequency count

0    10
1    20
2    10
3    30
4    40
5    30
6    50
dtype: int64
0    10
1    20
dtype: int64
5    30
6    50
dtype: int64
count     7.000000
mean     27.142857
std      14.960265
min      10.000000
25%      15.000000
50%      30.000000
75%      35.000000
max      50.000000
dtype: float64
27.142857142857142
190
10
50
[10 20 30 40 50]
10    2
30    2
20    1
40    1
50    1
Name: count, dtype: int64
